# Binomial distn

In [53]:
import numpy as np
import scipy
import scipy.stats
x=[0,1,2,3,4]
f=[28,62,46,10,4]
print(sum(f))
n=np.max(x);
N=np.sum(f)
print(n)
p=(np.average(x,weights=f))/n
d=scipy.stats.binom.pmf(x,n,p)
print(d)
ex=np.round(N*d,0)
print(ex)
print(sum(ex))
e=[30,59,44,17]
o=[28,62,46,14]
chi=0
for i in range(0,4):
    chi=chi+(((o[i]-e[i])**2)/e[i])
print(chi)
print(scipy.stats.chi2.ppf(0.95,2))
print(scipy.stats.chi2.sf(chi,2))

150
4
[0.19753086 0.39506173 0.2962963  0.09876543 0.01234568]
[30. 59. 44. 15.  2.]
150.0
0.9061965618296626
5.991464547107979
0.6356556577368107


# Poisson Distn

In [98]:
import scipy
from scipy.stats import poisson
import numpy as np
import scipy.stats
x=[0,1,2,3,4]
f=[211,90,19,5,0]
N=sum(f)
print(N)
a=np.average(x,weights=f)
print(a)
p=poisson.pmf(k=x,mu=a)
ex=np.round(N*p,0)
print(ex)

e=[209,92,24]
o=[211,90,24]
print(sum(e))
chi=0
for i in range (0,3):
    chi=chi+(((o[i]-e[i])**2)/e[i])
print(chi)
print(scipy.stats.chi2.ppf(0.95,1))
print(scipy.stats.chi2.sf(chi,1))

325
0.44
[209.  92.  20.   3.   0.]
325
0.06261701685042646
3.841458820694124
0.8024064518194011


# Geometeric Distn

In [107]:
from scipy.stats import geom
x=[0,1,2,3,4,5]
f=[450,132,41,22,3,2]
print(sum (f))
a=np.average(x,weights=f)
p=(1/(1+a))
print(p)
N=sum(f)
g=geom.pmf(x,p)
ex=np.round(N*g,0)
print(ex)
print(sum(ex))

650
0.6827731092436975
[  0. 444. 141.  45.  14.   4.]
648.0


# negative binomial

In [113]:
import numpy as np
import pandas
import scipy
x=[0,1,2,3,4,5]
f=[450,132,41,22,3,2]
a=np.average(x,weights=f)
v=[x,f].var()
print(v)


AttributeError: 'list' object has no attribute 'var'

# Normal Distn


In [155]:
import numpy as np
import scipy.stats
import math
l=[13.2,20.9,28.6,36.3,44.0,51.7,59.4,67.1,74.8,82.5,90.2]
f=[2,10,16,37,43,39,29,13,6,5]
x=[]
for i in range(0,len(l)-1):
    x.append(np.round((l[i]+l[i+1])/2,2))
print(x)
a=np.average(x,weights=f)
v=0
for i in range (0,len(x)):
    v=v+((f[i]*(x[i]-a)**2)/sum(f))
print(v)
p=scipy.stats.norm(a,math.sqrt(v)).cdf(l)
print(p)
pdf=[]
for i in range (0,len(l)-1):
    d=p[i+1]-p[i]
    pdf.append(d)
N=sum(f)
print(N)
pdf=np.array(pdf)
print(pdf)
ex=N*pdf
print(ex)
e=[3,8,19,33,42,40,29,16,10]
o=[2,10,16,37,43,39,29,13,11]
chi=0
for i in range (0,len(e)):
    chi=chi+((o[i]-e[i])**2)/e[i]
print(chi)
print(scipy.stats.chi2.ppf(0.95,5))
print(scipy.stats.chi2.sf(chi,5))

[np.float64(17.05), np.float64(24.75), np.float64(32.45), np.float64(40.15), np.float64(47.85), np.float64(55.55), np.float64(63.25), np.float64(70.95), np.float64(78.65), np.float64(86.35)]
203.24019099999998
[0.00413113 0.01781847 0.05926999 0.15367066 0.31536415 0.52368826
 0.72558932 0.87278223 0.95349764 0.98678624 0.99710981]
200
[0.01368734 0.04145152 0.09440068 0.16169349 0.20832411 0.20190105
 0.14719291 0.08071542 0.0332886  0.01032357]
[ 2.73746841  8.29030351 18.88013518 32.33869764 41.66482234 40.38021082
 29.43858145 16.14308369  6.65771905  2.06471318]
2.5031755525176576
11.070497693516351
0.77601675083272


# Lognormal Distn